services:
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    env_file: ${DPSRV_HOME}/rc/secrets/roundcube/roundcube.env
    ports:
      - 9000:9000
    volumes:
      - ${DPSRV_HOME}/srv/www/roundcube/:/var/www/html/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
