services:
  roundcube:
    image: roundcube/roundcubemail:latest-fpm-alpine
    container_name: roundcube
    env_file: ${DPSRV_HOME}/rc/secrets/roundcube/roundcube.env
    volumes:
      - ${DPSRV_HOME}/rc/secrets/mysql/conf.d/:/etc/mysql/conf.d1/
      - ${DPSRV_HOME}/srv/mysql/:/var/lib/mysql/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
