#!/bin/bash -e

. ../rc/secrets/mysql/mysql.env
. ../rc/secrets/roundcube/roundcube.env

CONTAINER_NAME=dpsrv-mysql-latest
docker exec -it $CONTAINER_NAME mysql -h $ROUNDCUBEMAIL_DB_HOST -P $ROUNDCUBEMAIL_DB_PORT -u root -p$MYSQL_ROOT_PASSWORD mysql -e "CREATE DATABASE IF NOT EXISTS $ROUNDCUBEMAIL_DB_NAME;"
docker exec -it $CONTAINER_NAME mysql -h $ROUNDCUBEMAIL_DB_HOST -P $ROUNDCUBEMAIL_DB_PORT -u root -p$MYSQL_ROOT_PASSWORD mysql -e "CREATE USER IF NOT EXISTS '$ROUNDCUBEMAIL_DB_USER'@'%' IDENTIFIED BY '$ROUNDCUBEMAIL_DB_PASSWORD';"
docker exec -it $CONTAINER_NAME mysql -h $ROUNDCUBEMAIL_DB_HOST -P $ROUNDCUBEMAIL_DB_PORT -u root -p$MYSQL_ROOT_PASSWORD mysql -e "GRANT ALL PRIVILEGES ON $ROUNDCUBEMAIL_DB_NAME.* TO '$ROUNDCUBEMAIL_DB_USER'@'%';"



